# Generated by Django 6.1 on 2026-08-21 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_appuser_managers_remove_appuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
            ],
        ),
    ]
